openapi: 3.0.0
info:
  title: Miro-like Collaborative Whiteboard API
  description: API for a collaborative whiteboard application similar to Miro
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


paths:

  /users/sign_in:
    post:
      $ref: "./endpoints/auth.yaml#/signIn"

  /users/sign_out:
    delete:
      $ref: "./endpoints/auth.yaml#/signOut"

  /users:
    get:
      $ref: "./endpoints/users.yaml#/getAllUsers"

  /clicks:
    get:
      $ref: "./endpoints/clicks.yaml#/getAllClicks"

  /promo_codes:
    get:
      $ref: "./endpoints/promo-codes.yaml#/getAllPromoCodes"

  /offers:
    get:
      $ref: "./endpoints/offers.yaml#/getAllOffers"

  /conversions:
    get:
      $ref: "./endpoints/conversions.yaml#/getAllConversions"

  /ads_managers:
    get:
      $ref: "./endpoints/ads-managers.yaml#/getAllAdsManagers"
    post:
      $ref: "./endpoints/ads-managers.yaml#/createAdsManager"

  /ads_managers/{adsManagerId}:
    get:
      $ref: "./endpoints/ads-managers.yaml#/getAdsManager"
    put:
      $ref: "./endpoints/ads-managers.yaml#/updateAdsManager"
    delete:
      $ref: "./endpoints/ads-managers.yaml#/deleteAdsManager"

  /ads_managers/{adsManagerId}/offers:
    get:
      $ref: "./endpoints/ads-managers.yaml#/getAdsManagerOffers"

  /ads_managers/{adsManagerId}/reports:
    get:
      $ref: "./endpoints/reports.yaml#/getAllReports"
    post:
      $ref: "./endpoints/reports.yaml#/createReport"

  /ads_managers/{adsManagerId}/reports/{reportId}:
    get:
      $ref: "./endpoints/reports.yaml#/getReport"
    put:
      $ref: "./endpoints/reports.yaml#/updateReport"
    delete:
      $ref: "./endpoints/reports.yaml#/deleteReport"


